kind: PersistentVolume
apiVersion: v1
metadata:
  name: fresco-pv
  labels:
    type: host-local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/fresco"
